import type { Metadata } from "next";
// import localFont from "next/font/local"; 
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry"; 
import { Montserrat } from 'next/font/google'


const montserrat = Montserrat({ weight: ['400', '500', '600', '700'], subsets: ['latin'] });

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "TradeCouples",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
      className={`${montserrat.className}`} suppressHydrationWarning={true}
      > 
       <AntdRegistry> 
        {children}
       </AntdRegistry>
      </body>
    </html>
  );
}
